milliondb/milliondb/milliondb/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('mysite.urls', namespace='mysite')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

milliondb/milliondb/mysite/urls.py
from django.conf.urls import url
from. import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detail/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
]

milliondb/milliondb/mysite/models.py
from django.db import models

class Idol(models.Model):
    name = models.CharField(max_length=50)
    yomigana = models.CharField(max_length=50)
    height = models.IntegerField()
    threeSize = models.CharField(max_length=20)
    birthday = models.CharField(max_length=20)
    cv = models.CharField(max_length=50)
    detail = models.TextField()
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.name

milliondb/milliondb/mysite/forms.py
from django import forms
from .models import Idol

class IdolForm(forms.Form):
    name = forms.CharField(label="名前")

milliondb/milliondb/mysite/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Idol
from .forms import IdolForm

def index(request):
    if request.method == 'GET':
        form = IdolForm()
        idols = Idol.objects.all()
    elif request.method == 'POST':
        form = IdolForm(request.POST)
        name = request.POST['name']
        idols = Idol.objects.all().filter(name__contains=name)
    return render(request, 'mysite/index.html', {'idols' : idols, 'form' : form } )

def detail(request, pk):
    idol = get_object_or_404(Idol, pk=pk)
    return render(request, 'mysite/detail.html', {'idol' : idol} )

milliondb/milliondb/mysite/templates/mysite/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>ミリオンDB</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" id="themesid">
    <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
    <script src="http://code.jquery.com/jquery-1.12.4.js" integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU=" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <style type="text/css">
      body {
        padding-top: 70px;
      }
    </style>
    {% block style %}
    {% endblock %}
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'mysite:index' %}">TOPへ</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

      {% block content %}
      {% endblock %}

    </div><!-- /.container -->
  </body>
</html>

milliondb/milliondb/mysite/templates/mysite/detail.html
{% extends 'mysite/base.html' %}

{% block content %}
  <div class="row">
    <div class="image col-md-4">
      <img src="{{ idol.image.url }}" class="img-responsive"/>
    </div>
    <div class="detail col-md-8">
      <table class="table table-bordered">
        <tbody>
          <tr>
            <td><strong>名前</strong></td>
            <td>{{ idol.name }}({{ idol.yomigana }})</td>
          </tr>
          <tr>
            <td><strong>誕生日</strong></td>
            <td>{{ idol.birthday }}</td>
          </tr>
          <tr>
            <td><strong>身長</strong></td>
            <td>{{ idol.height }}cm</td>
          </tr>
          <tr>
            <td><strong>声優</strong></td>
            <td>{{ idol.cv }}</td>
          </tr>
        </tbody>
      </table>
      <p class="h2">詳細</p>
      {{ idol.detail }}
    </div>
  </div>

{% endblock content %}

milliondb/milliondb/mysite/templates/mysite/index.html
{% extends 'mysite/base.html' %}

{% block style %}
<style>
.img-over{
  transition: 0.3s;
}

.img-over:hover{
  transform: scale(2.2);
}
</style>

{% endblock style %}

{% block content %}

<form action="" method="POST">
  {% csrf_token %}
  <label>名前:</label>
  {{ form.name }}
  <button type="submit">検索</button>
</form>

<div class="col-md-12">
{% if idols|length > 0 %}
    {% for idol in idols %}
    <div class="col-md-1">
      <a href="{% url 'mysite:detail' pk=idol.pk %}"><img src="{{ idol.image.url }}" class="img-responsive img-circle img-over"/></a>
    </div>
    {% endfor %}
{% else %}
    <p>検索結果は0件です。</p>
{% endif %}
</div>

{% endblock content %}